packaging_format = 2

id = "jirafeau"
name = "Jirafeau"
description.en = "Upload a file in a simple way and give a unique link to it"
description.fr = "Hébergez simplement un fichier et partagez-le avec un lien unique"

version = "4.6.2~ynh1"

maintainers = []

[upstream]
license = "AGPL-3.0-only"
demo = "https://demo.yunohost.org/jirafeau/"
code = "https://gitlab.com/jirafeau/Jirafeau"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = "all"
multi_instance = false

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/jirafeau"

    [install.init_main_permission]
    type = "group"
    default = "visitors"
    help.en = "⚠️ Beware that if this service is exposed to anonymous visitors, it *could* be used by robots for shady/illegal content hosting. However, you may need to expose this app publicly to be able to share links with people."
    help.fr = "⚠️ Attention, si ce service est exposé à des visiteurs anonymes, il *pourrait* être utilisé par des robots pour l'hébergement de contenus louches/illégaux. Cependant, il se peut que vous deviez exposer cette application publiquement pour pouvoir partager des liens avec d'autres personnes."
    
    [install.admin_user]
    ask.en = "Choose an admin user (will be able to access admin.php page)"
    ask.fr = "Choisissez l'administrateur (seul autorisé à accéder à la page admin.php)"
    type = "user"

    [install.upload_password]
    ask.en = "Set the password granting upload permissions (leave empty to allow anybody to upload). Please avoid using ' (quotes) in the password as it will fail the app..."
    ask.fr = "Définissez le mot de passe permettant l'accès à l'envoi de fichiers (laissez vide pour autoriser tout le monde). Veuillez éviter d'utiliser ' (guillemets) dans le mot de passe car cela fera échouer l'application..."
    type = "password"
    optional = true

[resources]
        [resources.sources.main]
        url = "https://gitlab.com/jirafeau/Jirafeau/-/archive/4.6.2/Jirafeau-4.6.2.tar.bz2"
        sha256 = "acef9cb8d7f432257471dd9f4bc4ad8a78c454837114e70a618c8cf96035af66"
        autoupdate.strategy = "latest_gitlab_tag"

    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.data_dir]
    subdirs = ["files", "links", "async", "block"]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "php8.3-fpm"
