packaging_format = 2

id = "jirafeau"
name = "Jirafeau"
description.en = "Upload a file in a simple way and give a unique link to it"
description.fr = "Hébergez simplement un fichier et partagez-le avec un lien unique"

version = "4.5.0~ynh1"

maintainers = []

[upstream]
license = "AGPL-3.0-only"
website = "https://gitlab.com/mojo42/Jirafeau"
demo = "https://demo.yunohost.org/jirafeau/"
code = "https://gitlab.com/mojo42/Jirafeau"
cpe = "???" # FIXME: optional but recommended if relevant, this is meant to contain the Common Platform Enumeration, which is sort of a standard id for applications defined by the NIST. In particular, Yunohost may use this is in the future to easily track CVE (=security reports) related to apps. The CPE may be obtained by searching here: https://nvd.nist.gov/products/cpe/search. For example, for Nextcloud, the CPE is 'cpe:2.3:a:nextcloud:nextcloud' (no need to include the version number)
fund = "???" # FIXME: optional but recommended (or remove if irrelevant / not applicable). This is meant to be an URL where people can financially support this app, especially when its development is based on volunteers and/or financed by its community. YunoHost may later advertise it in the webadmin.

[integration]
yunohost = ">= 11.0.9"
architectures = "all" # FIXME: can be replaced by a list of supported archs using the dpkg --print-architecture nomenclature (amd64/i386/armhf/arm64), for example: ["amd64", "i386"]
multi_instance = false
ldap = "?" # FIXME: replace with true, false, or "not_relevant". Not to confuse with the "sso" key : the "ldap" key corresponds to wether or not a user *can* login on the app using its YunoHost credentials.
sso = "?" # FIXME: replace with true, false, or "not_relevant". Not to confuse with the "ldap" key : the "sso" key corresponds to wether or not a user is *automatically logged-in* on the app when logged-in on the YunoHost portal.
disk = "50M" # FIXME: replace with an **estimate** minimum disk requirement. e.g. 20M, 400M, 1G, ...
ram.build = "50M" # FIXME: replace with an **estimate** minimum ram requirement. e.g. 50M, 400M, 1G, ...
ram.runtime = "50M" # FIXME: replace with an **estimate** minimum ram requirement. e.g. 50M, 400M, 1G, ...

[install]
    [install.domain]
    # this is a generic question - ask strings are automatically handled by Yunohost's core
    type = "domain"

    [install.path]
    # this is a generic question - ask strings are automatically handled by Yunohost's core
    type = "path"
    default = "/jirafeau"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin_user]
    ask.en = "Choose an admin user (will be able to access admin.php page)"
    ask.fr = "Choisissez l'administrateur (seul autorisé à accéder à la page admin.php)"
    type = "user"

    [install.upload_password]
    ask.en = "Set the password granting upload permissions (leave empty to allow anybody to upload). Please avoid using ' (quotes) in the password as it will fail the app..."
    ask.fr = "Définissez le mot de passe permettant l'accès à l'envoi de fichiers (laissez vide pour autoriser tout le monde). Veuillez éviter d'utiliser ' (guillemets) dans le mot de passe car cela fera échouer l'application..."
    type = "password"
    optional = true

[resources]
        [resources.sources.main]
        url = "https://gitlab.com/mojo42/Jirafeau/-/archive/4.5.0/Jirafeau-4.5.0.tar.gz"
        sha256 = "cc164f086b65c810cefc0eb26bffa6718a12a56ea94b7717d7eba8281d6c66ac"


    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"
