#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    # ------------
    # Tests to run
    # ------------

    # -------------------------------
    # Default args to use for install
    # -------------------------------

    args.admin_user = "package_checker"
    args.upload_password = "supersecretpassword"

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    #test_upgrade_from.0615fbcf.name = "Upgrade from 4.3.0~ynh3"
    test_upgrade_from.c686a51bdf1e1cce8c36b4cfdefb571135c8d2f3.name = "Upgrade from 4.6.1~ynh1"
