#sub_path_only rewrite ^__PATH__$ __PATH__/ permanent;
location __PATH__/ {

  # Path to source
  alias __INSTALL_DIR__/;

  index index.php;

  client_max_body_size 10G;
  client_body_timeout 30m;
  proxy_read_timeout 30m;

  try_files $uri $uri/ index.php;

  location ~ ^__PATH__/lib/functions.js.php {
    fastcgi_pass unix:/var/run/php/php__PHP_VERSION__-fpm-__APP__.sock;
    include fastcgi_params_no_auth;
    fastcgi_read_timeout 30m;
    fastcgi_send_timeout 30m;
  }

  location ~ ^__PATH__/lib/.*\.php {
    deny all;
  }

  location ~ [^/]\.php(/|$) {
    fastcgi_pass unix:/var/run/php/php__PHP_VERSION__-fpm-__APP__.sock;
    include fastcgi_params_no_auth;

  }
}
