#!/bin/bash

#=================================================
# GENERIC STARTING
#=================================================
# MANAGE FAILURE OF THE SCRIPT
#=================================================

# Exit on command errors and treat unset variables as an error
set -eu

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

if [ ! -e _common.sh ]; then
	# Rapatrie le fichier de fonctions si il n'est pas dans le dossier courant
	sudo cp ../settings/scripts/_common.sh ./_common.sh
	sudo chmod a+rx _common.sh
fi
source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# LOAD SETTINGS
#=================================================

app=$YNH_APP_INSTANCE_NAME

final_path=$(ynh_app_setting_get $app final_path)
domain=$(ynh_app_setting_get $app domain)

#=================================================
# STANDARD BACKUP STEPS
#=================================================
# BACKUP OF THE MAIN DIR OF THE APP
#=================================================

CHECK_SIZE "$final_path"
ynh_backup_abstract "$final_path" "sources"

#=================================================
# BACKUP OF THE DATA DIR
#=================================================

CHECK_SIZE "/home/yunohost.app/$app"
ynh_backup_abstract "/home/yunohost.app/$app" "data"

#=================================================
# BACKUP OF THE NGINX CONFIGURATION
#=================================================

ynh_backup_abstract "/etc/nginx/conf.d/$domain.d/$app.conf" "nginx.conf"

#=================================================
# BACKUP OF THE PHP-FPM CONFIGURATION
#=================================================

ynh_backup_abstract "/etc/php5/fpm/pool.d/$app.conf" "php-fpm.conf"
ynh_backup_abstract "/etc/php5/fpm/conf.d/20-$app.ini" "php-fpm.ini"
