#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# MODIFY URL IN NGINX CONF
#=================================================
ynh_script_progression "Updating NGINX web server configuration..."

ynh_config_change_url_nginx

#=================================================
# SPECIFIC MODIFICATIONS
#=================================================

# Change domain name in parameters.yml
ynh_replace --match="\$cfg\['web_root'\] = .*" --replace="\$cfg['web_root'] = 'https://' . '$new_domain' . '${new_path%/}' . '/';" --file="$install_dir/lib/config.local.php"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Change of URL completed for $app"
