#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# RETRIEVE ARGUMENTS FROM THE MANIFEST
#=================================================

ynh_app_setting_set --key=php_upload_max_filesize --value=10G

enable_crypt="false"
ynh_app_setting_set --key=enable_crypt --value=$enable_crypt

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"

ynh_safe_rm $install_dir/install.php

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_phpfpm

ynh_config_add_nginx

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration files..."

if [ "$path" = "/" ]
then
	jirafeau_path=""
else
	jirafeau_path="$path"
fi

ynh_config_add --template="config.local.php" --destination="$install_dir/lib/config.local.php"

#=================================================
# SET THE CRON FILE
#=================================================
ynh_script_progression "Configuring the cron file..."

ynh_config_add --template="cron" --destination="/etc/cron.d/$app"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
